services:

  concordance_web:
    container_name: concordance_web
    build: .
    restart: always
    volumes:
     - static_data:/app/static/
     - media_data:/app/media/
    env_file:
      - .env

  concordance_nginx:
    container_name: concordance_nginx
    image: nginx:1.21.3-alpine
    ports:
     - "80:80"
    volumes:
     - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
     - static_data:/var/html/static/
     - media_data:/var/html/media
    depends_on:
      - concordance_web
    env_file:
      - .env

volumes:
  static_data:
    name: static_data
  media_data:
    name: media_data